"""add captura_image to access_log

Revision ID: 39780dac575e
Revises: 545da33f8e36
Create Date: 2026-07-22 15:26:22.419283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39780dac575e'
down_revision: Union[str, Sequence[str], None] = '545da33f8e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('capture_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_logs', 'capture_image')
    # ### end Alembic commands ###
