"""update: columna de access_log

Revision ID: d0705c8aac8a
Revises: a0c5f81e7f52
Create Date: 2026-06-13 02:31:22.378620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0705c8aac8a'
down_revision: Union[str, Sequence[str], None] = 'a0c5f81e7f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('access_result', sa.String(), nullable=False))
    op.drop_column('access_logs', 'access_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('access_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('access_logs', 'access_result')
    # ### end Alembic commands ###
